# Generated by Django 6.0.3 on 2026-03-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='weight_unit',
            field=models.CharField(choices=[('lb', 'Lb')], default='kg'),
        ),
    ]
