# Generated by Django 6.0.3 on 2026-03-21 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='status',
            field=models.CharField(choices=[('Adopted', 'Adopted'), ('Pending', 'Pending'), ('Not-Adopted', 'Not-Adopted')]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
