# Generated by Django 6.0.3 on 2026-03-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_web', '0002_dog_weight_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('lb', 'Lb'), ('g', 'G')], default='kg'),
        ),
    ]
