# Generated by Django 6.0.3 on 2026-03-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_web', '0003_alter_dog_weight_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kiligrams (kg)'), ('lb', 'Pounds (lb)'), ('g', 'Grams {g}')], default=' kg'),
        ),
    ]
