# Generated by Django 6.0.3 on 2026-03-22 23:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_web', '0004_alter_dog_weight_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='age',
            new_name='age_year',
        ),
        migrations.AddField(
            model_name='dog',
            name='age_month',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AddField(
            model_name='dog',
            name='birthday',
            field=models.DateField(null=True, blank=True)
        ),
        migrations.AlterField(
            model_name='dog',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms (kg)'), ('lb', 'Pounds (lb)'), ('g', 'Grams (g)')], default='kg'),
        ),
    ]
