# Generated by Django 6.0.3 on 2026-03-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_web', '0005_rename_age_dog_age_year_dog_age_month_dog_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='birthday',
            field=models.DateField(null=True, blank=True),
        ),
    ]
