# Generated by Django 6.0.3 on 2026-03-24 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_web', '0006_alter_dog_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dog',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6),
        ),
        migrations.AlterField(
            model_name='dog',
            name='status',
            field=models.CharField(choices=[('Adopted', 'Adopted'), ('Pending', 'Pending'), ('Not-Adopted', 'Not-Adopted')], max_length=11),
        ),
    ]
