# Generated by Django 6.0.3 on 2026-04-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_web', '0007_alter_dog_age_month_alter_dog_age_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dogs/'),
        ),
    ]
