# Generated by Django 6.0.3 on 2026-04-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_web', '0008_dog_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('street', models.CharField()),
                ('city', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('interested_dog', models.CharField()),
                ('phone', models.CharField(max_length=15)),
                ('housing', models.CharField(choices=[('Own', 'Own'), ('Rent', 'Rent')])),
                ('signiture', models.ImageField(upload_to='')),
            ],
        ),
    ]
