# Generated by Django 6.0.3 on 2026-04-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_web', '0009_adoptation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptation',
            name='signiture',
        ),
        migrations.AddField(
            model_name='adoptation',
            name='comment',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='adoptation',
            name='state',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='adoptation',
            name='yard',
            field=models.CharField(choices=[('yes_fenced', 'Yes Fenced'), ('yes_unfenced', 'Yes Unfenced'), ('No', 'No')], default=''),
        ),
        migrations.AddField(
            model_name='adoptation',
            name='zip',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='adoptation',
            name='housing',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('Other', 'Other')], default=''),
        ),
    ]
